url: https://manfontan.github.io/language-learning-hub/
baseurl: /language-learning-hub/

# Site settings
title: Language Learning Hub
email: my@email.com
description: "where language happens"
title-short: "LLH"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: slack
    url: https://unlimitedperf-qxk1768.slack.com/join/shared_invite/zt-ewd5hazp-VmeI_CdWpPo4rj6Ifz1ArA#/
  - title: github
    url: http://github.com/manfontan

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty

header-image: /img/header.jpg

# Jekyll plugins for seo, and content indexing
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag