# The icons are <fab fa-icon_name> 
# We are using fa icons if you want to add more search https://fontawesome.com/icons?d=gallery
header: We have amazing services (Label 4)
list:
- name: Cambridge Exam Lessons (online)
  icon: fas fa-book-open
  description: FCE - CAE - CPE
- name: English Lessons (online)
  icon: fa fa-laptop
  description: General English and Business English Lessons - All levels
- name: English Lessons in Ireland
  icon: fas fa-globe-europe
  description: Learn English while discovering the Emerald Island
- name: German Lessons (online)
  icon: fas fa-comments
  description: German without walls
- name: Italian Lessons (online)
  icon: fas fa-edit
  description: Sharp that Italian accent like a pro without leaving your home.
- name: Spanish Lessons (online)
  icon: fas fa-chalkboard-teacher
  description: Learning Spanish is cool, but learning Spanish online... ole! 
  
